// <auto-generated />
using System;
using BakeTherapie.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakeTherapie.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917232709_SeedInitialProducts")]
    partial class SeedInitialProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BakeTherapie.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FulfillmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("MarketingOptIn")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BakeTherapie.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BakeTherapie.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PromotionalTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaglineShort")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            ImageUrl = "/images/closeups/ruth-chocolate-chips.png",
                            IsAvailable = true,
                            Name = "Ruth's Chocolate Chips",
                            Price = 4.50m,
                            PromotionalTags = "",
                            Summary = "Rich brown butter dough loaded with semi-sweet and Belgian dark chocolate.",
                            TaglineShort = "Cookie drop classic"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            ImageUrl = "/images/closeups/ash-daily-matcha.png",
                            IsAvailable = true,
                            Name = "Ash's Daily Matcha",
                            Price = 4.50m,
                            PromotionalTags = "",
                            Summary = "Earthy matcha paired with smooth Belgian white chocolate.",
                            TaglineShort = "Earthy and creamy"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            ImageUrl = "/images/closeups/charlie-triple-chocolate.png",
                            IsAvailable = true,
                            Name = "Charlie's Triple Chocolate",
                            Price = 4.50m,
                            PromotionalTags = "",
                            Summary = "Rich cocoa cookie loaded with three varieties of chocolate.",
                            TaglineShort = "For chocolate lovers"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 3,
                            ImageUrl = "/images/closeups/lotso-strawberry-basket.png",
                            IsAvailable = true,
                            Name = "Lotso's Strawberry Basket",
                            Price = 4.50m,
                            PromotionalTags = "",
                            Summary = "Sweet cookie bursting with bright, strawberry flavor.",
                            TaglineShort = "Bright and fruity"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 4,
                            ImageUrl = "/images/closeups/garfield-morning-brew.png",
                            IsAvailable = true,
                            Name = "Garfield's Morning Brew",
                            Price = 4.50m,
                            PromotionalTags = "",
                            Summary = "Bold Japanese coffee cookie topped with toasted almond slivers.",
                            TaglineShort = "Bold coffee hit"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 5,
                            ImageUrl = "/images/closeups/earl-rubies.png",
                            IsAvailable = true,
                            Name = "Earl's Rubies",
                            Price = 4.50m,
                            PromotionalTags = "",
                            Summary = "Fragrant Earl Grey cookie dotted with tart dried cranberries.",
                            TaglineShort = "Fragrant tea notes"
                        });
                });

            modelBuilder.Entity("BakeTherapie.Api.Models.OrderItem", b =>
                {
                    b.HasOne("BakeTherapie.Api.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeTherapie.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BakeTherapie.Api.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
